#!/command/with-contenv sh
# ==============================================================================
# Start nginx reverse proxy
# ==============================================================================

echo "[tabulate] Starting nginx..."

exec nginx -g "daemon off;" -c /etc/nginx/nginx.conf
