name: Validate integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hassfest:
    name: hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS (${{ matrix.category }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        category: [integration, template]
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: ${{ matrix.category }}
          ignore: brands
